# 开发环境配置文件
"""
Django settings for meiduo_mall project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_brr#3n7c+i=)k)ksh8+g#j32-l6h55jzawa#9m5!^p6$o1u)e"

# SECURITY WARNING: don't run with debug turned on in production!
# 开发者模式,上线之后改为False
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "meiduo_mall.urls"

TEMPLATES = [
    # {
    #     "BACKEND": "django.template.backends.django.DjangoTemplates",
    #     "DIRS": [os.path.join(BASE_DIR, 'templates')],
    #     "APP_DIRS": True,
    #     "OPTIONS": {
    #         "context_processors": [
    #             "django.template.context_processors.debug",
    #             "django.template.context_processors.request",
    #             "django.contrib.auth.context_processors.auth",
    #             "django.contrib.messages.context_processors.messages",
    #         ],
    #     },
    # },
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2", # 配置Jinja2模版引擎
        "DIRS": [os.path.join(BASE_DIR, 'templates')], # 配置模版文件加载的路径
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            
            # 补充jinja2模版引擎环境
            'environment': 'meiduo_mall.utils.jinja2_env.jinja2_environment'
        },

},
    
]

WSGI_APPLICATION = "meiduo_mall.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# 配置网络数据库
DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }
    # 修改数据库为mysql
    "default": {
        "ENGINE": "django.db.backends.mysql", # 数据库引擎
        "HOST": '39.98.194.30', # 数据库主机
        "PORT": 3306,   # 数据库端口
        "USER": 'xieanning',    # 数据库用户名
        "PASSWORD": '123456',   # 数据库密码
        "NAME": 'meiduo_mall'   # 数据库名字
    }
}

# 配置缓存数据库--redis数据库
CACHES = {
    "default": {    # 默认缓存到0号库
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://39.98.194.30:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
     "session": {   # session缓存到1号库
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://39.98.194.30:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },

    }
}
# session缓存到1号库
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
